package com.rodriguezst.farmacia;


import java.util.ArrayList;

import com.rodriguezst.farmacia.ItemContainer;

import android.os.Bundle;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ArrayAdapter;
//import android.view.Menu;
import android.widget.Filter;
import android.widget.Filterable;
import android.widget.ListView;
import android.widget.SearchView;
import android.widget.TextView;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
//import android.widget.TextView;
import android.widget.Toast;

public class MainActivity extends Activity implements SearchView.OnQueryTextListener {
	
	private SearchView mSearchView;
    private ListView mListView;

    public final static String ITEM_UID = "com.rodriguezst.farmacia.ITEM_UID";
    public final static String ITEM_NAME = "com.rodriguezst.farmacia.ITEM_NAME";
    public final static String ITEM_DATA = "com.rodriguezst.farmacia.ITEM_DATA";
    
 
    private Filter mFilter = null;
    private ArrayAdapter<ItemContainer> mArrayAdapter;
    
    private ArrayList<ItemContainer> mDatabase;
    private ArrayList<ItemContainer> mDatabaseBackup;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		
		mListView = (ListView) findViewById(R.id.list_view);
		mSearchView = (SearchView) findViewById(R.id.search_view);
		
		readDatabase();
		
		//mListView.setTextFilterEnabled(true);
		mArrayAdapter = new ItemAdapter(this,R.layout.list_item_1, mDatabase);
		mFilter = mArrayAdapter.getFilter();
		mListView.setAdapter(mArrayAdapter);
		
		mSearchView.setIconifiedByDefault(false);
        mSearchView.setOnQueryTextListener(this);
        //mSearchView.setSubmitButtonEnabled(true); 
		
        mListView.setOnItemClickListener(new OnItemClickListener() {
			public void onItemClick(AdapterView<?> parent, View view,
					int position, long id) {
			    // When clicked, open the selected item
			    itemOpen(position);
			}
		});
        
	}

	
	private void itemOpen(int position){
		//This should take you to another activity passing the selected item
		if(position<mDatabase.size()){
			ItemContainer item = mDatabase.get(position);
			
			Toast.makeText(getApplicationContext(),"This would open the product page for " + item.getName(), Toast.LENGTH_SHORT).show();
			int mUID = item.getUID();
			String mName = item.getName();
			Intent intent = new Intent(MainActivity.this, ProductDetail.class);
			intent.putExtra(ITEM_UID, mUID);
			intent.putExtra(ITEM_NAME, mName);
			/*Bundle extras = new Bundle();
			extras.putSerializable(ITEM_DATA, mDatabase.getItem(position));
			intent.putExtras(extras);*/
			startActivity(intent);
		}else{
			Log.i("Carlos", "Pointer error! Position: " + position + " Array Size: " + mDatabase.size());
		}
	}
	
	public boolean onQueryTextChange(String newText) {
//        if (TextUtils.isEmpty(newText)) {
//            mListView.clearTextFilter();
//        } else {
//            mListView.setFilterText(newText.toString());
//        }
        mFilter.filter(newText.toString());
        return true;
    }
 
	public boolean onQueryTextSubmit(String query) {
        //mFilter.filter(query.toString());
		if(mDatabase.size()>0)
			itemOpen(0);
        return true;
    }
	
	
	private void readDatabase() {
		mDatabase = new ArrayList<ItemContainer>();
		mDatabaseBackup = new ArrayList<ItemContainer>();

		//read database
		//String data[] = {"Avila","Burgos","Le—n","Palencia","Salamanca","Segovia","Soria","Valladolid","Zamora"};
		String data[] = {"ACECLOFENACO 100MG 10T","METROCLOPRAMIDASol Iny c/6","ABOB+ACETAMINOFEN+FENILEFRINA+CLORFENAMINA12 TAB","ABOB+CLORFENAMINA+DIPIRONA 3ML AMP","ABOB+FENILEFRINA+CLORFENAMINA JBE 100ML","ACARBOSA 50 MG C/30 TAB","ACICLOVIR 200 MG C/25 CPR","ACICLOVIR SUSP","ACICLOVIR 400 MG C/35 CPR","ACICLOVIR CRA 5 MG","ACIDO ACETIL SALICILICO 500MG + CAFEINA 30MG 40T","ACIDO ACETIL SALICILICO 500MG C/20 TAB","ACIDO ACETILSALICILICO 100MG C/30 TAB","ACIDO ACETILSALICILICO 300MG C/20 TAB EFERV","ACIDO ALENDRONICO 10MG 30TAB","ACIDO ALENDRONICO 70MG C/4 TAB","ACIDO FOLICO+HIERRO+PROTEINAS SOYA 30T","ACIDO FOLICO+HIERRO+VITAMINAS 40T","ACIDO GLUTAMICO 600 MG C/100","ACIDO MEFENAMICO 500MG C10 TAB","ACIDO MEFENAMICO 500MG C20 TAB","ACIDO NALIDIDIXICO+FENAZOPIRIDINA 20T","ACIDO NALIDIXICO SUSP","ACIDO NALIDIXICO TAB C20/500","ACIDO RETINOICO CRA 0.050% 30GR","ACIDO RISEDRONATO 35MG 4T","AESCULUS HIPOCASTANUM T30","ALBENDAZOL 200MG C/6 TAB","ALBENDAZOL SUSP","ALGESTONA+ESTRADIOL 1 AMP 1ML","ALOPURINOL 300MG C/20 TAB","ALUMINIO Y MAGENESIO+DICICLOVERINA+DIMETICONA 30T MAST","ALUMUMINIO+MAGNESIO SUSP 240ML","ALUMUMINIO+MAGNESIO+DIMETICONA SUSP 240ML","AMANTADINA+CLORFENIRAMIDA+PARACETAMOL C/15TAB","AMBROXOL GOTAS 30ML","AMBROXOL C/20 TAB","AMBROXOL SOL 120ML","AMBROXOL+CLENBUTEROL GTS 20ML","AMBROXOL+CLENBUTEROL SOL 120ML","AMBROXOL+CLENBUTEROL C/20 TAB","AMBROXOL+DEXTROMETORFANO 10 TAB","AMBROXOL+LEVODROPROPIZINA 120ML","AMBROXOL+OXELADINA SOL 120ML","AMBROXOL+SALBUTAMOL 120ml","AMBROXOL-LORATADINA JBE 120ML","AMBROXOL-LORATADINA T10","AMIKACINA 100MG AMP1","AMIKACINA 500MG C/1 AMP","AMIODARONA 200MG T20","AMLODIPINO 5MG C/10 TAB","AMLODIPINO 5MG C/30 TAB","AMOXICIL+AMBROX 250 MG /15MG SUSP","AMOXICILINA 250MG C12","AMOXICILINA 250MG SUSP 75ML","AMOXICILINA 500MG 12C","AMOXICILINA 500MG/5ML SUSP","AMOXICILINA 125 MG SUSP","AMOXICILINA+AC CLAV 125/31.25MG SUSP","AMOXICILINA+AC CLAV 200MG SUSP","AMOXICILINA+AC CLAV 400 JR SUSP 60ML","AMOXICILINA+AC CLAV 500MG C/10TAB","AMOXICILINA+AMBROXOL C16 500MG","AMOXICILINA+BROMEXINA C12","AMOXICILINA+BROMHEXINA SUSP 250/8MG 5ML 16C","AMOXICILINA+SULBACTAM 250/250MG 5ML 60ML","AMOXIXILINA+AC. CLAV 875/125 /10T","AMPICILINA 1.0 GR AMP","AMPICILINA 125MG SUSP 90ML","AMPICILINA 500MG SUSP 60ML","AMPICILINA 1GR INY","AMPICILINA 250MG 20C","AMPICILINA 250MG SUSP 60ML","AMPICILINA 500MG C20","AMPICILINA 500MG INY","AMPICILINA+DICLOXACILINA 60ML SUSP. 125MG/62.5/5ML","AMPICILINA+DIPIRONA+CLORFENIRAMINA+GUAINESINA+LIDOCAINA AD C/3 AMP","AMPICILINA+DIPIRONA+CLORFENIRAMINA+GUAINESINA+LIDOCAINA INF C/3 AMP","ASTEMIZOL SUSP 200MG","ASTEMIZOL TABS C/10 10MG","ATENOLOL 50 MG C/28","AZITROMICINA 500MG C/3T","AZITROMICINA SUSP","BECLOMETASONA DIPROPIONATO SPRAY AEROSOL","BENCIDAMIDA CLORIDRATO DE 30 ML","BENCIDAMIDA CLORIDRATO DE 360ML","BENCIDAMIDA CRA 5% 60GR","BENCILPENICILINA PROCAINA Y CRISTALINA 400000UI AMP","BENCILPENICILINA PROCAINA Y CRISTALINA 800000UI AMP","BENCILPENICILINA+BENZATINA COMP 1 AMP 3ML","BENZATINA+BENCILPENICILINA 1 200 000 UI","BENZOCAINA FRAMBUESA C/24","BENZOCAINA,CLORANFENICOL,HIDROCORTISONA GTS 5ML","BENZONATATO C/20 PERLAS","BETAMETASONA 4 MG/ML","BETAMETASONA CREMA 30GR","BETAMETASONA+CLOTRIMAZOL+GENTAMICINA 40GR","BEZAFIBRATO 200MG C/30TAB","BEZOCAINA 10GR GEL","BICALUTAMIDA 50MG C28","BROMHEXINA AD JBE 100ML","BROMHEXINA INF JBE 100ML","BROMOCRIPTINA 2.5MG C/14TAB","BRONKORUB UNG 40G","BUTILHICINA+METAMIZOL C/10GRAG","BUTILHICINA+METAMIZOL C/3AMP","BUTILHICINA+METAMIZOL GTS 20ML","BUTILHIOSCINA C/3AMP","BUTILHIOSCINA GTS 15ML","BUTILHIOSCINA C/10GRAG","CALCIO EFERV. C/12CPS","CALCIO VIC 600MG 30T","CALCIO+MAGNESIO 30T","CALCIO+VITAMINA D SUSP","CALCIO+VITAMINA D T60","CALCITRIOL 0.25MCG 50 CAP","CAOLIN+PECTINA+FURAZOLIDONA SUSP 120ML","CAPTOPRIL 25MG 30T","CAPTOPRIL 50MG 20T","CAPTOPRIL+HIDROCLOROTIAZIDA 15T","CARBAMAZEPINA 10T 400 MG","CARBAMAZEPINA 120ML SUSP","CARBAMAZEPINA 20 TAB/200 MG","CARNITINA C/30","CARNITINA+B1+AMONOACIDOS C/30","CEFACLOR 125 MG SUSP","CEFACLOR 250MG C/15CAP","CEFACLOR 250MG SUSP","CEFACLOR 375 MG 10T 12HRS","CEFACLOR 375MG SUSP","CEFACLOR 500MG C/15CAP","CEFACLOR 750 MG 10T","CEFADROXILO 500MG C/16CAP","CEFADROXILO 250MG SUSP","CEFALEXINA 125MG SUSP","CEFALEXINA 250MG SUSP","CEFALEXINA 500MG C/20 CAP","CEFOTAXIMA 1.0GR IV","CEFOTAXIMA 1GR IM","CEFTRIAXONA 1.0GR IM G I","CEFTRIAXONA 500MG IM G I","CEFUROXIMA 250MG SUSP","CEFUROXIMA 125 MG SUSP","CEFUROXIMA 250MG T10","CEFUROXIMA 500MG T10","CETIRIZINA 10 MG TABS C/10","CETIRIZINA SOL 50ML","CIANOCOBOLAMINA F A 12ML","CIMETIDINA T30 300MG","CINARIZINA TAB 75MG C/60","CINITAPRIDA 1GR C25","CIPROFLOXACINO 250MG C/12TAB","CIPROFLOXACINO 500 MG 8T","CIPROFLOXACINO INY 200MG/100ML","CIPROFLOXACINO SOL.OFT 5MG","CISAPRIDA 10MG C/30TAB","CISAPRIDA 5MG C/30TAB","CISAPRIDA SUSP 60 ML. 1 MG/ML","CITALOPRAM 20MG 14T","CLARITROMICINA 125MG SUSP","CLARITROMICINA 250MG C/10TAB","CLARITROMICINA 250MG SUSP 60ML","CLARITROMICINA 500MG C/10TAB","CLENBUTEROL .02MG 50T","CLINDAMICINA 300 MG C/16","CLINDAMICINA 600MG C/1 AMP.GI","CLINDAMICINA CRA VAGINAL 40 GR","CLINDAMICINA GEL 30 GR","CLORANFENICOL SOL OFT 10ML","CLORANFENICOL500MG 20T","CLORFENAMINA 4MG T20","CLORFENAMINA 50MG JBE 120 ML","CLORFENAMINA+PARACETAMOL+FENILEFRINA+CAFEINA 10 TAB","CLORFENAMINA+PARACETAMOL+FENILEFRINA+VITAMINA C 12TAB","CLORFENIRAMIDA+DEXAMETASONA JBE 60ML","CLORFENIRAMINA+DEXAMETASONA 12T","CLORFENIRAMINA+FENILEFRINA 120 ML AD E INF","CLORMADINONA 2MG 20T","CLORMADINONA+MESTRANOL 2MG 20T","CLORTALIDONA 20T 50MG","CLORURO DE SODIO+GLICEROL 30ML AD","CLORURO DE SODIO+GLICEROL 30ML INF","CLORURO DECALINO+HIDROCORTIZONA+TIROTRICINA+LIDOCAINA 20ML SOL","CLOTRIMAZOL C/6 CPR VAG","CLOTRIMAZOL CRA 2% VAGINAL 20GR","CLOTRIMAZOL CRA 30GR","COLCHICINA TAB C/30 GI","COMPLEJO B T30","COMPLEJO B 5-AMP","COMPLEJO B+DEXAMETASONA INY/2","COMPLEJO B+DEXAMETASONA T/12","COMPLEJO B+DEXAMETASONA+LIDOCAINA SOL INY 3AMP","COMPLEJO B+DICLOFENACO AMP/3","CORTILONA CRA 30GR","DANAZOL 100MG 50T","DEFLAZACORT 30MG 10T","DEFLAZACORT 6MG 20T","DESLORATADINA 5MG 10T","DESLORATADINA 5MG 30T","DESOGESTREL+ETINILESTRADIOL","DEXAM+NEOM+LIDOC OTICA GTS 10ML","DEXAM+NEOM+POLI SOL OFTALM 5 ml","DEXAM+NEOMICINA OFT GTS 5ML","DEXAMETASONA 0.5MG T/30","DEXAMETASONA INY C/1","DEXAMETASONA INY C/3 AMP","DEXAMETASONA+FENILBUTAZONA+METOCARBAMOL G30","DEXAMETASONA+FENILBUTAZONA+SALICILAMIDA+GEL HIDROXIDO 20T","DEXAMETASONA+NEOMI+FENILEFRINA GTS NASAL","DEXTROMETORFANO 300MG JBE 120 ML","DEXTROMETORFANO+AMBROXOL AD 120ML","DEXTROMETORFANO+GUAYFENESINA ADULTO","DEXTROMETORFANO+GUAYFENESINA INFANTIL","DEXTROMETORFANO+PARACETAMOL+FENILEFRINA GRANULADO C/6 SBS","DEXTROMETORFANO+PARACETAMOL+FENILEFRINA T10","DICICLOVERINA 10MG 30T","DICICLOVERINA+ALUMINIO+MAGNESIO+DIMETICONA 30T","DICLOCACICLINA SOL INY 250 MG","DICLOFENACO 100MG 20T","DICLOFENACO CRA 60GR","DICLOFENACO GI INY C/2","DICLOFENACO GI INY C/4","DICLOFENACO SODICO 1MG GTS 5 ML","DICLOFENACO SODICO SUSP 120ML","DICLOFENACO+BETAMETASONA GEL 60GR","DICLOFENACO+CARISIPRODOL 20G","DICLOFENACO+COMPLEJO B-50 MG/30 G","DICLOFENACO+PARACETAMOL 10C 50/500MG","DICLOXACILINA 250 MG C20","DICLOXACILINA 250 MG SUSP 60ML","DICLOXACILINA 500MG C12","DIFENHIDRAMINA 250MG JBE 120ML","DIFENHIDRAMINA 25MG C30","DIFENIDOL 25 MG 30T","DIFENIDOL AMP-2","DIGOXINA 0.250 MG C/24","DILTIAZEM 30 TAB/30 MG","DIMENHIDRINATO 24 T 50MG","DIMENHIDRINATO GTS INF 15ML","DIMENHIDRINATO INY 50 MG/3","DIMENHIDRINATO SUP INF C/5","DIMETICONA SUSP 100MG 30ML","DIPROPIONATO+FOSFATO DE BETAMETASONA 4MG 1AMP","DOXICICLINA 100MG 10 CAPS","ELECTROLIT COCO 500 ML","ELECTROLIT FRESA 500ML","ELECTROLIT MZA 500ML","ELECTROLIT PED COCO 500 ml","ELECTROLIT PED FRESA 625ML","ELECTROLIT PED LIM/LIMON 4S","ELECTROLIT PED MANZ PLAST 625 ml","ELECTROLIT PED PI„A 625ML","ELECTROLITO 4SBS LIMON","ELECTROLITO 4SBS MANZANA","ELECTROLITO 4SBS NARANJA","ELECTROLITO 4SBS PI„A","ENALAPRIL T/30 10MG","ERITROMICINA 250MG SUSP","ERITROMICINA 500MG 20T","ERITROMICINA T 250 MG C/20","ESPIRONOLACTONA 25MG 20T","ESTROGENOS CONJ 0.625 C/21 GRAG","ESTROGENOS CONJ 0.625 C/42 GRAG","EUCALIPTO,GUAYACOL PERLAS30","EUCALIPTO+GUAYACOL,+MIEL+GORDOLOBO+PROPOLEO+BUGAMBILIA+VIT C ADT 240 ML","EUCALIPTO+GUAYACOL,+MIEL+GORDOLOBO+PROPOLEO+BUGAMBILIA+VIT C INF 240 ML","EUCALIPTO-+MIEL+GORDOLOBO+MIRRA+MENTOL CARAMELOS","EUCALIPTO-+MIEL+GORDOLOBO+MIRRA+MENTOL PALETAS","EUCALIPTO-MIRRA-PROPOLEO-MIEL 240 ML JBE","EXALVER FENILEFRINA PED. 30 ML","EXTRACTO CASTA„A INDIAS 500MG 30T","FAMOTIDINA 20MG 30C","FELODIPINO 5 MG 20T","FENAZOPIRIDINA 100 MG C/20 TAB","FENILEFRINA+DEXAMETASONA+NEOMICINA NASAL","FENITOINA SODICA 250 MG/5 ML","FENITOINA SODICA 7.5MG 120ML","FENITOINA T50 100MG","FEXOFENADINA C/10 120MG","FEXOFENADINA C/10 180MG","FINASTERIDA 5MG 30T","FLUCINOLONA+CLIOQUINOL CRA 30G","FLUCINOLONA+NEOMICINA CRA 30G","FLUCONAZOL 150MG. 1C","FLUCONAZOL 10 T 100MG","FLUCONAZOL 2 T 150MG","FLUNARICINA 10 MG T20","FLUNARICINA 5MG T/40","FLUOCINOLONA CREMA 30G","FLUOCINOLONA+METRONIDAZOL+NISTATINA OV/10","FLUOXETINA 20 MG C/14","FLUOXETINA 20 MG C/28","FOCUS VERSICULOSUS+GARCINA CAMBOGIA+POLINICOTINATO DE CR 60 CPS","FUMARATO FERROSO SUSP 120ML","FUMARATO FERROSO C50 200MG","FUMARATO FERROSO+ACIDO FOLICO C30","FUROSEMIDA 40 MG C/20","FUROSEMIDA 20MG C/20 INY","GABAPENTINA 300 MG C/15","GENTAMICINA 20 MG 1 AMP","GENTAMICINA 160MG C/5 AMP","GENTAMICINA 80 MG S-INY 5X2","GENTAMICINA 80 MG S-INY C/1","GINKO YANG CAPS C/30","GLIBENCLAMIDA 5 MG C/50","GLIBENCLAMIDA METFORMINA 500/5MG T30","GLIBENCLAMIDA+METFORMINA 2.5/500MG G30","GLIMEPIRIDA 2MG C30","GLIMEPIRIDA 4MG T30","GLIMEPIRIDA+METFORMINA 1/500MG 32T","GLUCOSAMINA 30C 500MG","GLUCOSAMINA 90 C 500MG","GLUCOSAMINA+CONDROITINA C/30 T","GUAIFENESINA+OXOLAMINA JBE 140ML AD","GUAIFENESINA+OXOLAMINA JBE INF 60ML","GUAYACOL AMPOLLETA 1ML","HIDRALAZINA 20T 10MG","HIDROCLOROTIAZIDA 25 MG 20TAB","HIDROCORTISONA CRA 30GR","HIDROX--MAGNESIO+ALUMINIO 240ML","HIDROXOCOBALAMINA 100MG 2ML AMP","HIERRO DEXTRANO AMP4","HIPROMELOSA 0.5% SOL OFT 15ML","HIPROMELOSA 2% SOL OFT 15ML","IBUPROFENO 400MG T10","IBUPROFENO 600MG. C10","IBUPROFENO 200 MG C/10","IBUPROFENO 800 MG C/10","IBUPROFENO SUSP 120 ML","IBUPROFENO+CAFEINA 10T","INDOMETACINA C30","INDOMETACINA+BETAMETASONA+METOCARBAMOL 25/0.75/215MG 20C","ISOCONAZOL CR 20GR GI","ISOSORBIDE 10MG T/20","ITRACONAZOL 100 MG C/15","ITRACONAZOL+SECNIDAZOL 33.3 MG CAP16","KETOKONAZOL CRA 30GR","KETOKONAZOL SHAMPOO 120 ml","KETOKONAZOL TAB10 200MG","KETOPROFENO 100MG C15","KETOPROFENO 100MG 6X2AMP","KETOPROFENO+PARACETAMOL 12T 100/300MG","KETOPROFENO+PARACETAMOL SUSP 120ML","KETOROLACO 4T 30MG SUBLINGUAL","KETOROLACO C/10 TAB 10MG","KETOROLACO C/3 AMP 30MG","KETOROLACO+TRAMADOL 10C","KETOTIFENO C/30","KETOTIFENO SOL 120ML","LACTOBACILOS ACIDOFILOS C/40","LACTULOSA 125ML","LAMOTRIGINA 100MG TAB 28","LAMOTRIGINA 25 MG TAB 28","LANSOPRAZOL 15 MG C/14","LANSOPRAZOL 30MG 14T","LECHE DE MAGNESIA 180ML","LEVETIRACETAM","LEVOFLOXACINO 500MG C/7 TAB","LEVONORGESTREL 1.5MG /1 TAB","LEVONORGESTREL+ETINILESTRADIOL C/21","LEVONORGESTREL+ETINILESTRADIOL C/28","LEVOTIROXINA 100MCG C100","LEVOTIROXINA 125MCG C100","LEVOTIROXINA 50MCG C100","LIDOCAINA 10% 115ML SPRAY","LIDOCAINA 2% 50ML","LIDOCAINA UNG 35GR","LIDOCAINA+HIDROCORTISONA+SUB/ALUMINIO+OXIDO/ZIN 12 SUPS","LIDOCAINA+HIDROCORTISONA+SUB/ALUMINIO+OXIDO/ZINC UNG 30GR","LINCOMICINA 600 MG INY C/3","LINCOMICINA INF 300 MG C/6 AMP","LINCOMICINA T16/500 MG","LISINA CLOHRIDRATO 125MG T10","LISINA CLOHRIDRATO 250MG T10","LISINA+BUTILHIOSCINA INY 2ML C/6","LISINA+BUTILHIOSCINA T10 250/10MG","LISINA+BUTILHIOSCINA T20 125/10MG","LISINOPRIL T/30 10 MG","LOPERAMIDA T/12 2MG","LORATADINA FENILEFRINA INF JBE 60ML","LORATADINA FENILEFRINA JBE AD 120ML","LORATADINA SOL 60 ML 5MG/5ML","LORATADINA SOL GTS 30 ml","LORATADINA T/10 10MG","LORATADINA+BETAMETASONA 5/.25MG T/10","LORATADINA+BETAMETASONA SOL 100 MG 60 ML","LOSARTAN 50MG C/10T","LOSARTAN 50MG C/30 TAB","LOSARTAN+HIDROCLOROTIAZIDA 50/12.5 30 T","MECLIZINA PIRIDOXINA GTS 15ML","MECLIZINA PIRIDOXINA SOL 5-AMP","MECLIZINA PIRIDOXINA T/12","MEDROXI PROGESTERONA ESTRADIOL INY AMP1","MELOXICAM 15 MG INY C/3","MELOXICAM 15MG C/10","MELOXICAM 7.5 MG C/14","MELOXICAM 7.5MG C/7","METAMISOL 500 MG T10","METAMIZOL 2ML 3AMP","METAMIZOL GTS 30 ML","METAMIZOL INY 2.5GR 5ML","METAMIZOL JBE 120 ML 250MG","METENAMINA 30T 500MG","METFORMINA 850MG T30","METFORMINA+CLORPROPAMIDA 500/125MG 30T30","METILDOPA 250 MG 30 TAB","METILPREDNISOLONA 500MG","METOCARBAMOL+ACETILSALISILICO C18","METOCARBAMOL+MELOXICAM T10","METOCLOPRAMIDA T/20 10MG","METOPROLOL 20T/100","METROCLOPRAMIDA GTS 20 ML","METRONIDAZOL 250 MG TAB C/20","METRONIDAZOL 250MG/5ML 120 ML","METRONIDAZOL 500 MG T30","METRONIDAZOL 500 MG/100 ML","METRONIDAZOL INY BOLSA 500MG 100ML","METRONIDAZOL+DIYODOHIDROXIQUINOLEINA SUSP 120ML","METRONIDAZOL+DIYODOHIDROXIQUINOLEINA T20","MICONAZOL 20 GR CRA","MICRODACYN 60 SOL 240ML","MINOCICLINA 100MG 10T","MULTIVITAMINAS Y MINERALES C60","NAFAZOLINA SOL OFT 15 ml","NAFAZOLINA+FENIRAMINA 5ML","NAFAZOLINA+SULFACETAMIDA 20ML","NAPROXENO 250 MG TAB C/30","NAPROXENO 500 MG C/10 TAB","NAPROXENO SODICO 100/2.5 SUSP","NAPROXENO SODICO 275 MG T20","NAPROXENO+CARISOPRODOL 250/200MG 30CAP","NAPROXENO+PARACETAMOL C10T","NAPROXENO+PARACETAMOL SUSP","NEOM/POLIMIX/GRAMIC 15 ML GTS","NEOM+CAOLIN+PECTINA 120ML","NEOMICINA+DEXAMETASONA SOL 5ML","NIFEDIPINO 10 MG C/20","NIFEDIPINO 30 MG 30 CPS","NIMESULIDA 25MG 20ML","NIMESULIDA 50MG 60ML","NIMESULIDA 100MG CAPS","NIMESULIDA GEL 40GR","NISTATINA GI C/12 TAB","NISTATINA SUSP 24ML","NISTATINA+TRIAMCINALONA CRA 40G","NITAZOXANIDA 200 MG T6","NITAZOXANIDA 500 MG T6","NITROFURAL 6MG 6/OV","NITROFURANTOINA C40 100MG","NORFLOXACINO T20 400MG","NORFLOXACINO-FENAZOPIRIDINA C/8","OFLOXACINO 400 MG C/8","OMEPRAZOL 20 MG C/14","OMEPRAZOL 20 MG C/7","OMEPRAZOL 20 MG C120","OMEPRAZOL 20 MG C2","OMEPRAZOL 20 MG C60","OMEPRAZOL SOL INY 40MG","ONDANSETRON 8MG C10T","ONDANSETRON 8MG/4ML AMP 3","OPUNTIA FICUS-NOPAL DESHIDRATADO 150T","ORLISTAT / 21 CAP 120 MG","OXIDO DE ZINC TUBO PASTA 30GR","OXIDO DE ZINC TUBO PDA 60GR","OXIMETAZOLINA 20ML SOL ADU+GLICERINA","OXIMETAZOLINA 20ML SOL INF","OXITETRACICLINA 125MG TROCISCOS C24","OXITETRACICLINA 16C 500MG","OXOLAMINA JBE 100ML","PANCREATINA+BILIS DE BUEY+DIMETILPOLISILOXANO G25","PANTOPRAZOL 40MG C/14","PARACETAMOL 300MG C/5 SUP","PARACETAMOL 500 T10","PARACETAMOL 750MG T10","PARACETAMOL 80MG 4T","PARACETAMOL GOTAS 15ML","PARACETAMOL GTS 30 ML","PARACETAMOL JBE 120 ML","PARACETAMOL,FENILEFRINA, CLORFENIRAMINA 12GRA","PARACETAMOL,FENILEFRINA, CLORFENIRAMINA 30ML","PARACETAMOL,FENILEFRINA, CLORFENIRAMINA JBE","PARACETAMOL+CAFEINA 10 T","PARACETAMOL+FENILEFRINA+LORATADINA SOBRE PVO/6","PARACETAMOL+IBUPROFENO 325/200MG 20T","PAROXETINA T/10 20MG","PENICILINA V POT 400000U 20T","PENICILINA V POT 800 000 U 20T","PENTOXIFILINA 400MG T30","PERBORATO+BITARTRATO DE Na 1 SOBRE","PERBORATO+BITARTRATO DE Na 20 SOBRES","PINAVERIO BROMURO DE 100 MG 14T","PIROXICAM 20MG T20","PIROXICAM 30 GM CRA","PLANTAGO PSYLLIUM 400GR. GI","PRAVASTATINA 10 MG C/15","PRAVASTATINA10 MG C/30","PREDNISOLONA 5MG SOL OFT 5 ML","PREDNISONA 20MG C30 TAB GI","PREDNISONA 5 MG TAB C/20","PREDNISONA 50MGC/20 TAB GI","PROGESTERONA+ESTRADIOL 50/5 AMP","PROPAFENONA 150 MG/20 TAB","PROPANOLOL 40 MG C/20 TAB","PROPOLEO+EUCALIPTO+SAUCO+MENTOL+GORDOLOBO+EQUINACEA FREE SUGAR 150ML","PROPOLEO+EUCALIPTO+SAUCO+MENTOL+GORDOLOBO+EQUINACEA FREE SUGAR 35GR","PROTEINAS+CREATINA 500 GR 30T","PROTEINAS+MULTIVITAMINICO SABOR CHOCOLATE 237 ML","PROTEINAS+MULTIVITAMINICO SABOR FRESA 237 ML","PROTEINAS+MULTIVITAMINICO SABOR VAINILLA 237 ML","PRUEBA DE EMBARAZO","QUINFAMIDA 100 MG 3TAB","QUINFAMIDA SUSP. 100ML","RAMIPRIL 16 TAB/5 MG","RANITIDINA 300 MG C/10","RANITIDINA 150 MG C/20","RANITIDINA 50MG 2MLX5AMP","RANITIDINA GOTAS","RANITIDINA INY 5AMP","RANITIDINA JBE 200ML","RIFAMPICINA 300 MG C/16 CAP","SAL DE UVAS PICOT","SALBUTAMOL 4MG T30","SALBUTAMOL GI AERO 100MCG","SALBUTAMOL JBE 40 MG 120 ML","SENOSIDOS A y B C20","SENOSIDOS AyB C30 +CIRUELA","SERTRALINA 50MG C/14 T","SIBUTRAMINA 10 MG C15","SIBUTRAMINA 15 mg c/15","SIBUTRAMINA 15 MG C30","SILDENAFIL 50MG C/1-TAB","SILDENAFIL 50MG C/4-TAB","SIMVASTATINA 10 MG C14","SUBSALICILATO/BISMUTO SUSP 120ML","SUCRALFATO 40 TAB/1G","SULFADIAZINA DE PLATA CRA 28GR","SULINDACO 200MG/20 TAB","TAMOXIFENO 10MG 30T","TAMSULOSINA 0.4 MG CAPS 20","TEOFILINA 20 TAB/100 MG","TERBINAFINA 1% CRA 20 GR","TERBINAFINA 28T 250MG","TERBINAFINA 7 T 250MG","TERRAMICINA TROCISCOS C24 125MG","TETRACICLINA 250MG 10T","TIAMAZOL 5MG 20T","TIBOLONA 2.5MG 30T","TINIDAZOL 500MG 8T","TOLBUTAMIDA 50T 500MG","TOLTERODINA 2MH 14T","TOPIRAMATO 100MG 20T","TOPIRAMATO 25MG","TRAMADOL 100MG 5AMP","TRAMADOL 10T/50 MG","TRAMADOL+PARACETAMOL+V B1+V B12 20T","TRETINOINA 30G CREMA 0.05%","TRIMEBUTINA 100MG/5ML SUSP","TRIMEBUTINA SOL GTS 30 Mml","TRIMEBUTINA200 MG C/20 TAB","TRIMETOPRIM+SULFAMETOXAZOL 1600/800 TAB C/20","TRIMETOPRIM+SULFAMETOXAZOL 40 MG SUSP 120ML","TRIMETOPRIM+SULFAMETOXAZOL 80/400 TAB C/20","VALERIANA+PASIFLORA+AVENA+MUERDAGO T40","VALPROATO DE MAGNESIO 40T 200MG","VALPROATO DE MAGNESIO SUSP","VANCOMICINA 500MG SOL INY","VERAPAMILO 80 MG/20 TAB","VITAMINA C C20 TAB 100MG","VITAMINA C 10T 1GR EFERVESENTE","VITAMINA E 400 MG C90 CAPS","VITAMINA E 600 MG C/30 CAPS","VITAMINA P/DIABETICOS 30T","VITAMINA+OMEGA 3 30T","VITAMINAS A C Y D 3AMP/3ML ING","VITAMINAS A C Y D GTS 15 ML","VITAMINAS A C Y D GTS 30 ML","VITAMINAS A Y D +ACEITE/TIBURON 30 T","VITAMINAS EMBARAZO 9 MESES C30","VITAMINAS --LECITINA DE SOYA-- 60CPS","VITAMINAS Y MINERALES 30-30T","VITAMINAS Y MINERALES HOMBRE 60T","VITAMINAS Y MINERALES MUJER 30T","VITAMINAS, MINERALES, ANTIOXIDANTES Y OMEGA3 30CAP","VITAMINICO GERIATRICO C30","VITAMINICO INF JBE240ML","VITAMINICO T MAST 90","VITAMINICO+ISOFLAVONAS/SOYA C/30","VITIS VINIFERA (UVA) 60C","YODOPOVIDONA 120ML"};
		for (int i=0; i < data.length ; i++){
			//truncate long strings
			if(data[i].length()>25)
				data[i]= data[i].substring(0, 25) + "...";
			mDatabase.add(new ItemContainer(data[i], i));
		}
		//finished reading database
		mDatabaseBackup.addAll(mDatabase);
    }

	/* Removed options menu
	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.main, menu);
		return true;
	}*/
	
	public class ItemAdapter extends ArrayAdapter<ItemContainer> implements Filterable{
		
		
		public ItemAdapter(Context context, int resource, ArrayList<ItemContainer> items) {
			super(context, resource, items);
		}
		
		@Override
		public View getView(int position, View convertView, ViewGroup parent){
			View mView = convertView;
			
			if(mView == null){
				LayoutInflater inflater = (LayoutInflater) MainActivity.this.getLayoutInflater();
				mView = inflater.inflate(R.layout.list_item_1, parent, false);
			}
			if(position<mDatabase.size()){
				TextView mTextView = (TextView) mView.findViewById(R.id.text1);
				ItemContainer item = mDatabase.get(position);
				if(item!=null)
					mTextView.setText(item.getName());
			}
			
			return mView;
		}
		
		@Override
	    public Filter getFilter() {
	        return new Filter() {
				
				@Override
				protected void publishResults(CharSequence constraint, FilterResults results) {
					if (results.count > 0) {
						   mDatabase.clear();
				           mDatabase.addAll((ArrayList<ItemContainer>) results.values);
				           notifyDataSetChanged();
				          } else {
				        	  //TODO: Ask the client the expected behavior
				        	  //if uncommented all items in mDatabase will be shown after no results
				              //notifyDataSetInvalidated();
							  mDatabase.clear();
				        	  notifyDataSetChanged();
				          } 
					
				}
				
				@Override
				protected FilterResults performFiltering(CharSequence constraint) {
					FilterResults filterResults = new FilterResults();
					ArrayList<ItemContainer> results = new ArrayList<ItemContainer>();
					
					if(constraint!=null && mDatabaseBackup!=null){
						for(int i=0; i<mDatabaseBackup.size(); i++){
							if(mDatabaseBackup.get(i).getName().toLowerCase().matches("(.*)" + constraint.toString().toLowerCase() + "(.*)")){
								results.add(mDatabaseBackup.get(i));
							}
						}
						filterResults.values = results;
						filterResults.count = results.size();
					}
					return filterResults;
				}
			};
	    }

	}

}

